import { SizePropsType } from '../../utils/helpers'

export type IconName =
    | 'placeholder'
    | 'eye'
    | 'eye-close'
    | 'calendar'
    | 'chevron-left'
    | 'chevron-right'
    | 'chevron-down'
    | 'double-chevron-right'
    | 'double-chevron-left'
    | 'orders'
    | 'bank'
    | 'archive'
    | 'check'
    | 'close'
    | 'minus'
    | 'search'
    | 'exit'
    | 'filter'
    | 'filter-fill'
    | 'sorting'
    | 'sorting-reverse'
    | 'time'
    | 'warning-fill'
    | 'check-fill'
    | 'close-fill'
    | 'plus'
    | 'warning'
    | 'menu'
    | 'question-fill'
    | 'copy'
    | 'save'
    | 'trash'
    | 'update'

export type IconSize = Extract<SizePropsType, 's' | 'm' | 'l'>
